export const ROUTES = {
    LOGIN: '/login',
    SIGNUP: '/signup',
    DASHBOARD: '/dashboard',
    TRANSACTIONS: '/transactions',
    TRANSFER: '/transfer',
    WITHDRAW: '/withdraw',
    DEPOSIT: '/deposit',
    CARDS: '/cards',
    LOANS: '/loans',
    PROFILE: '/profile',
    NOTIFICATIONS: '/notifications',
    ADMIN_PANEL: '/admin',
    USER_MANAGEMENT: '/admin/users',
    EMPLOYEE_DASH: '/employee',
    EMPLOYEE_PROFILE: '/employee/profile',
    UNAUTHORIZED: '/unauthorized',
    NOT_FOUND: '*',
}
